### ISSUE TITLE
Manage Posts and Comments

### ISSUE THREAD

**Issue by j0hanz** [j0hanz/blog-beat-web#2]
As a **Site Owner**, I want to manage posts and comments submitted by users to ensure content quality and relevance.

### Acceptance Criteria 1:
- The site owner can view or reject posts and comments from the

### Acceptance Criteria 2:
- Rejected posts and comments will not be visible on the site.

## Tasks

- [x] Task 1: Allow the site owner to view posts and comments.
- [x] Task 2: Allow the site owner to reject posts and comments.
- [x] Task 3: Hide rejected posts and comments from the site.
