### ISSUE TITLE
Like button

### ISSUE THREAD

**Issue by j0hanz** [j0hanz/blog-beat-web#5]
As a **User**, I want to like blog posts to engage with the content.

### Acceptance Criteria 1:
- The user can click a "Like" button on any post.

### Acceptance Criteria 2:
- The total number of likes is updated immediately after a user likes a post.

## Tasks

- [ ] Task 1: Add a "Like" button to each post.
- [ ] Task 2: Implement functionality for users to like a post.
- [ ] Task 3: Update the total number of likes immediately after a post is liked.
