### ISSUE TITLE
Comment on posts

### ISSUE THREAD

**Issue by j0hanz** [j0hanz/blog-beat-web#6]
As a **User**, I want to comment on blog posts to engage with the content and other users.

### Acceptance Criteria 1:
- The user can write and submit comments on specific posts.

### Acceptance Criteria 2:
- The user can delete their own comments.

## Tasks

- [x] Task 1: Create a comment section for each post.
- [ ] Task 2: Implement functionality for users to submit comments.
- [ ] Task 3: Implement functionality for users to delete their own comments.
